source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'YURT' do
  pod 'RxSwift', '~> 4.0'
  pod 'RxAlamofire'
  pod 'Alamofire', '~> 4.7'  
  pod 'SDWebImage', '~> 4.0'
  pod "EasyDi"
  pod 'KeychainSwift', '~> 10.0'
end

